# Generated by Django 4.1 on 2022-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliacion',
            name='FechaFin',
            field=models.DateField(null=True),
        ),
    ]
