# Generated by Django 4.1 on 2022-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaApp', '0002_alter_afiliacion_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Genero',
            field=models.CharField(choices=[('Masc', 'Masculino'), ('Fem', 'Femenino'), ('Otr', 'Otro')], max_length=10),
        ),
    ]
