# Generated by Django 4.1 on 2022-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario1', models.IntegerField()),
                ('usuario2', models.IntegerField()),
                ('fecha', models.DateField()),
                ('mensaje', models.CharField(max_length=1400)),
            ],
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
