# Generated by Django 4.1 on 2022-09-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0002_mensaje_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
